src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\IRoles;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Annotations\DocLexer;
use DateTime;


/**
 * @ORM\Entity
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(
 *     fields={"email", "username"}
 * )
 * Permet d'avoir une cession de connexion au site.
 */
class User implements UserInterface, IRoles
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank()
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=150, unique=true)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;

    /** @ORM\Column(type="datetime") */
    private $modify;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(min=8)
     */
    private $plainPassword;

    /**
     * @ORM\Column(type="string", length=250)
     */
    private $password;

    /**
     * @ORM\Column(type="array")
     */
    private $roles;

    private $nbCommand;

    /**
     * @ORM\Column(type="integer")
     */
    private $archieved;

    /**
     * @ORM\Column(type="boolean", options={"default":"0"})
     */
    private $admin;

    /**
     * @ORM\Column(type="boolean", options={"default":"0"})
     */
    private $fctRDV;

    /**
     * @ORM\Column(type="boolean", options={"default":"0"})
     */
    private $fctInteret;

        /**
     * @ORM\Column(type="boolean", options={"default":"0"})
     */
    private $fctCadeau;

        /**
     * @ORM\Column(type="boolean", options={"default":"0"})
     */
    private $fctCourse;

        /**
     * @ORM\Column(type="boolean", options={"default":"0"})
     */
    private $fctConnaissance;

        /**
     * @ORM\Column(type="boolean", options={"default":"0"})
     */
    private $fctAppartement;

    public function __construct()
    {
        $this->roles = array(self::ROLE_MEMBER);
        $this->created = new DateTime('now');
        $this->modify = new DateTime('now');
        $this->setArchieved(false);
        $this->fctInteret = false;
        $this->fctCadeau = false;
        $this->fctCourse = false;
        $this->fctConnaissance = false;
        $this->fctAppartement = false;
        $this->fctRDV = false;
    }

    public function getUsername()
    {
        return $this->username;
    }

    public function setUsername($username)
    {
        $this->username = $username;
    }

    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email): void
    {
        $this->email = $email;
    }

    /**
     * @return mixed
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * @return mixed
     */
    public function getModify()
    {
        return $this->modify;
    }

    /**
     * @param mixed $modify
     */
    public function setModify($modify): void
    {
        $this->modify = $modify;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword($password)
    {
        $this->password = $password;
    }

    public function getSalt()
    {
        return null;
    }

    public function getRoles()
    {
        return $this->roles;
    }

    public function eraseCredentials()
    {
    }

    public function addRole($role){
        $this->roles[]= $role;
    }

    /**
     * @return mixed
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * @param mixed $lastname
     */
    public function setLastname($lastname): void
    {
        $this->lastname = $lastname;
    }

    /**
     * @return mixed
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * @param mixed $firstname
     */
    public function setFirstname($firstname): void
    {
        $this->firstname = $firstname;
    }

    /**
     * @return mixed
     */
    public function getNbCommand()
    {
        return $this->nbCommand;
    }

    /**
     * @param mixed $nbCommand
     */
    public function setNbCommand($nbCommand): void
    {
        $this->nbCommand = $nbCommand;
    }

    public function getCompleteName()
    {
        return $this->getFirstname(). " " . $this->getLastname();
    }

        /**
     * @param mixed $nbCommand
     */
    public function setArchieved($archieved): void
    {
        $this->archieved = $archieved;
    }
    
    public function getArchieved()
    {
        return $this->archieved;
    }

    function setAdmin($admin) {
        $this->admin = $admin;
    }

    function getAdmin(){
        return $this->admin;
    }

    /**
     * @param mixed $fctInteret
     */
    public function setFctInteret($interet): void
    {
        $this->fctInteret = $interet;
    }
    
    public function getFctInteret()
    {
        return $this->fctInteret;
    }

    /**
     * @param mixed $fctConnaissance
     */
    public function setFctConnaissance($fctConnaissance): void
    {
        $this->fctConnaissance = $fctConnaissance;
    }
    
    public function getFctConnaissance()
    {
        return $this->fctConnaissance;
    }

    /**
     * @param mixed $fctCourse
     */
    public function setFctCourse($fctCourse): void
    {
        $this->fctCourse = $fctCourse;
    }
    
    public function getFctCourse()
    {
        return $this->fctCourse;
    }

    /**
     * @param mixed $fctCadeau
     */
    public function setFctCadeau($fctCadeau): void
    {
        $this->fctCadeau = $fctCadeau;
    }
    
    public function getFctCadeau()
    {
        return $this->fctCadeau;
    }

    /**
     * @param mixed $fctAppartement
     */
    public function setFctAppartement($fctAppartement): void
    {
        $this->fctAppartement = $fctAppartement;
    }
    
    public function getFctAppartement()
    {
        return $this->fctAppartement;
    }

    /**
     * @param mixed $fctRDV
     */
    public function setFctRDV($fctRDV): void
    {
        $this->fctRDV = $fctRDV;
    }
    
    public function getFctRDV()
    {
        return $this->fctRDV;
    }

    function addRoleAdm(){
        $this->addRole("ROLE_ADMIN");
    }

}

src/Form/UserType.php
<?php


namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class)
            ->add('username', TextType::class)
            ->add('lastname', TextType::class)
            ->add('firstname', TextType::class)
            ->add('plainPassword', RepeatedType::class, array(
                'type' => PasswordType::class,
                'first_options' => array('label' => 'Password'),
                'second_options' => array('label' => 'Repeat Password'),
            ))
            ->add('submit', SubmitType::class, [
                "label" => "_submitRegister",
                'translation_domain' => 'form'
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => User::class,
        ));
    }
}

templates/Security/Admin/User/manage.html.twig
{% extends "Security/Admin/admin_homepage.html.twig" %}

{% block admin_body %}
    <div class="">
        {% if objects is not null and objects is defined %}
            <table class="table is-fullwidth is-hoverable">
                <thead>
                <tr>
                    <th>
                        <abbr title="Identifier">
                            Identifier
                        </abbr>
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        <abbr title="Description">
                            Créé le
                        </abbr>
                    </th>
                    <th>
                        <abbr title="Date">
                            nombre de commande
                        </abbr>
                    </th>
                    <th>
                        <abbr title="Actions">
                            Actions
                        </abbr>
                    </th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th><abbr title="number">Identifiant</abbr></th>
                    <th>Name</th>
                    <th><abbr title="Price">Créé le</abbr></th>
                    <th><abbr title="Date">Nombre de commande</abbr></th>
                    <th><abbr title="Actions">Actions</abbr></th>
                </tr>
                </tfoot>
                <tbody>
                {% for object in objects %}
                    <tr>
                        <th>{{ object.id }}</th>
                        <td>
                            {{ object.getCompleteName }}
                        </td>
                        <td>
                            {{ object.created|date("m/d/Y") }}
                        </td>
                        <td>
                             {{ object.nbCommand }}
                        </td>
                        <td>
                            <a href=""
                               class="button is-info is-outlined">
                                Edition
                            </a>
                            <a href=""
                               class="button is-link is-outlined">
                                Archivage
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div>
                <a href="{{ path("add_category") }}" class="button is-primary is-outlined">
                    Ajouter Category
                </a>
            </div>
            <table class="table is-centered">
                <thead>
                <tr>
                    <th>
                        <abbr title="Identifier">
                            ID
                        </abbr>
                    </th>
                    <th>
                        Label
                    </th>
                    <th>
                        <abbr title="Description">
                            Description
                        </abbr>
                    </th>
                    <th>
                        <abbr title="Description">
                            Date de création
                        </abbr>
                    </th>
                    <th>
                        <abbr title="Description">
                            Actions
                        </abbr>
                    </th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th><abbr title="identifier">Identifier</abbr></th>
                    <th>Nom</th>
                    <th><abbr title="Price">Créé le</abbr></th>
                    <th><abbr title="Price">Nombre commande</abbr></th>
                    <th><abbr title="Price">Actions</abbr></th>
                </tr>
                </tfoot>
                <tbody>
                {% for object in objects %}

                        <tr>
                            <th>{{ object.id }}</th>
                            <td>
                                {{ object.completeName }}
                            </td>
                            <td>
                                {{ object.created|date("m/d/Y") }}
                            </td>
                            <td>
                                {{ object.nbCommand }}
                            </td>
                            <td>
                                <a href=""
                                   class="button is-info is-outlined">
                                    a venir
                                </a>
                            </td>
                        </tr>

                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="separation-base">
                <span class="tag is-light is-warning font-size">
                    existe aucun user
                </span>
            </div>
        {% endif %}

        <div>
            <a href="" class="button is-primary is-outlined">
                Ajouter User
            </a>
        </div>
    </div>
{% endblock %}